teaheaven/config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users

  resources :orders
  resources :order_items
  resources :carts
  resources :teas

  root 'store#index', as: 'store'  #default location will be the catalogue

  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/store' => 'store#index'  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/previousorders' => 'orders#index' 

end

teaheaven/app/controllers/store_controller.rb
class StoreController < ApplicationController

  include CurrentCart
  before_action :set_cart

  def index

#    if params[:sortBy] == 'price'
 #     @teas = Tea.order('price')
  #  elsif params[:sortBy] == 'country'
   #   @teas = Tea.order('country')
    #else
     # @teas = Tea.order('name')
    #end

    if params[:search] 
      @teas = Tea.search(params[:search])
    else
      @teas = Tea.all()
    end
    @teas = @teas.order("created_at ASC")

  end


end

teaheaven/app/helpers/store_helper.rb
module StoreHelper
end

teaheaven/app/views/store/index.html.erb
<!-- admin user won't have a cart -->
<% if !current_user || (current_user && !current_user.isAdmin?) %> 
  <div class="col-m-12 col-3" id="cart">
    <%= render @cart %>
  </div>
<% end %>

<div class="col-m-12 col-9 mainTeaContent">

  <% if current_user && current_user.isAdmin? %> 
    <%= link_to 'New Tea', new_tea_path %>
  <% else %>
    <div id="search">
      <%= form_tag(teas_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search], :placeholder => "Search" %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  <% end %>

  <% cache ['store', Tea.latest] do %>
    <% @teas.each do |tea| %>
      <% cache ['entry', tea] do %>  
        <%= image_tag(tea.image_url, :class=>'teaImg', :title=>tea.name, :alt=>'Image of tea') %>
        <h3><%= tea.name %></h3><p>Strength: <%= tea.strength %><br/>Country of Origin: <%= tea.country %></p>

        <%= sanitize(tea.description) %>
        <div class="price_line">
          <span class="price"><%= number_to_currency(tea.price) %> per 100g</span>
          <% if current_user && current_user.isAdmin? %> 
            <%= link_to 'Edit', edit_tea_path(tea) %>
            <%= link_to 'Destroy', tea, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% elsif user_signed_in? %>
            <% if tea.stock? %>
              <%= button_to 'Add to Cart', order_items_path(tea_id: tea), remote: true %>
            <% else %>
              <p>Out of Stock!</p>
            <% end %>
          <% end %>
        </div>
	<p class="footerTop">
          <a href="#top">Top</a>
	</p>
	<hr/>
    <% end %>
  <% end %>
<% end %>
</div>