teaheaven/config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users

  resources :orders
  resources :order_items
  resources :carts
  resources :teas

  root 'store#index', as: 'store'  #default location will be the catalogue

  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/store' => 'store#index'  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/previousorders' => 'orders#index' 

end

teaheaven/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

teaheaven/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.user_id = current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end

  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ensure_admin
    unless current_user && current_user.isAdmin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end

  def signedinuserprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to "/profiles/new"
    else
      @profile = Profile.find_by_user_id(current_user.id)
      redirect_to "/profiles/#{@profile.id}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address1, :address2, :address3, :address4, :address5, :telephone, :user_id)
    end
end

teaheaven/app/helpers/profiles_helper.rb
module ProfilesHelper
end

teaheaven/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :address3 %><br>
    <%= f.text_field :address3 %>
  </div>
  <div class="field">
    <%= f.label :address4 %><br>
    <%= f.text_field :address4 %>
  </div>
  <div class="field">
    <%= f.label :address5 %><br>
    <%= f.text_field :address5 %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

teaheaven/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

teaheaven/app/views/profiles/index.html.erb
<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= link_to 'Show', profile %></td>

        <% if current_user && current_user.isAdmin? %> 
          <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
          <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && !current_user.isAdmin? %> 
  <% if user_signed_in? %>
    <%= link_to 'New Profile', new_profile_path %>
  <% end %>
<% end %>

teaheaven/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

teaheaven/app/views/profiles/show.html.erb
<div class="col-m-12 col-6">
Your profile details:
<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @profile.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @profile.address2 %>
</p>

<p>
  <strong>Address3:</strong>
  <%= @profile.address3 %>
</p>

<p>
  <strong>Address4:</strong>
  <%= @profile.address4 %>
</p>

<p>
  <strong>Address5:</strong>
  <%= @profile.address5 %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @profile.telephone %>
</p>

</div>
<% if current_user && current_user.isAdmin? %>
 <%= link_to 'Edit', edit_profile_path(@profile) %> 
<% end %>