teaheaven/config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users

  resources :orders
  resources :order_items
  resources :carts
  resources :teas

  root 'store#index', as: 'store'  #default location will be the catalogue

  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/store' => 'store#index'  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/previousorders' => 'orders#index' 

end

teaheaven/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :tea
  belongs_to :cart

  def total_price
    tea.price * quantity
  end
end

teaheaven/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]


  def breakdown(theOrderID)
    @order_items = OrderItem.where("order_id = ?", theOrderID)
  end

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
#@order_items = OrderItem.where("order_id =?", @order_id_test)
  end


  # GET /order_items/1
  # GET /order_items/1.json
  def show
@order_items = OrderItem.where("order_id = 19")
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    tea = Tea.find(params[:tea_id])
   # @order_item = @cart.order_items.build(tea: tea)
    @order_item = @cart.add_tea(tea.id)
    
    respond_to do |format|
      if @order_item.save
        format.html { redirect_to store_url }
        format.js {@current_item = @order_item }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:tea_id)
    end
end

teaheaven/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

teaheaven/app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tea_id %><br>
    <%= f.text_field :tea_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

teaheaven/app/views/order_items/_order_item.html.erb
<% if order_item == @current_item %>
<div id="current_item">
<% else %>
<div>
<% end %>
<ul>
<li><%= order_item.quantity %> &times <%= order_item.tea.name %> <%= number_to_currency(order_item.total_price) %> </li>
</ul>
</div>

teaheaven/app/views/order_items/breakdown.html.erb
<p>test this</p>

teaheaven/app/views/order_items/create.js.erb
$('#notice').hide();

$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#FFFFFF'},1000);

teaheaven/app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

teaheaven/app/views/order_items/index.html.erb
<h1>Listing Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Tea</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.tea %></td>
        <td><%= order_item.cart %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

teaheaven/app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

teaheaven/app/views/order_items/show.html.erb
<p>
  <strong>Tea:</strong>
  <%= @order_item.tea %>
id is <%= @order_item.order_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @order_item.cart %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>